### ISSUE TITLE
Pcb design

### ISSUE THREAD

**Issue by Roeland54** [FreeVario/FreeVario#1]
Hello,

I was in the starting phase of my own open source paragliding vario project with an e-paper display when I found your repository. It seems like the goals I had set for my project are more than fulfilled by yours. 
I would love to make a FreeVario and maybe contribute to your project. I have the following questions:

- Can you add the pcb designs and maybe a bill of materials to the repository so I can start to build a FreeVario?
- Can you add The STL files for the 3d printed case to the repository.
- Do you plan on further developing the project?

**Comment by primaldev** [comment]
Hi Roeland, thanks for your interest. I've added the files to the repository. You can use the eagle files if you need to modify the design, otherwise use the already prepared gerber files. All the parts is available from your nearest Chinese webshop (I kind of designed it for that). 

At the moment it is still flying season so not much is done at the moment. I might pick it up again in the winter.

I had some bad luck with the pcb. I ordered a pcb with 1mm thickness and it turned out not being able to dissipate the heat of the charging chip properly and ended up tearing loose from the board. So advise at the moment is to use a thicker pcb.

**Comment by Roeland54** [comment]
Hi, I finally picked this back up. Pcb and parts are ordered. Can you share the CAD files for the case? I may need to do some adjustments to the case to accommodate the thicker pcb. I also made the traces between the GND pad of the charging chip and the ground plane wider to improve thermal conductivity.

**Comment by primaldev** [comment]
I sent you an email with a link to the project files on tinkercad.

**Comment by thechillicherry** [comment]
Hey primaldev,
did you allready try the device? I found it like roeland54 i was looking for a vario which works with xctrack. 
can you tell me where you ordered the components?
cheers thechillicherry

**Comment by primaldev** [comment]
> Hey primaldev,
> did you allready try the device? I found it like roeland54 i was looking for a vario which works with xctrack.
> can you tell me where you ordered the components?
> cheers thechillicherry

Hi, thanks for your interest, yes, I stil use it time to time, but have switched to another device (Mipfly). All the components should still be available from aliexpress. But keep in mind, this project requires a lot of skill and time and patience. This project had a smooth start, but I had a lot of last minute problems and just ran out of time for the season start and had to buy a commercial vario. You should be familiar with STM32 processors and coding, otherwise troubleshooting will be very difficult. Also, the LoRa should be left out. Turns out it was wired the wrong way around (Datasheet were incorrect/unclear). 

A lot have changed the last few years with a lot of new players and projects on the market. Maybe, first have a look at [https://www.paraglidingforum.com/viewforum.php?f=39](https://www.paraglidingforum.com/viewforum.php?f=39) for other options.

But if you are up for the challenge, I suggest contacting Roeland as well, he did some improvements on the PCB.

**Comment by ra1amx** [comment]
Hi. You can add a BOM file and a component coordinate file to order a board on a production type jlcpcb.com 
Thanks!
